---
trigger:
  - main
jobs:
  - job: Terraform_Init
    steps:
      - script: "make init"
  - job: Terraform_Plan
    steps:
      - script: "make plan"
      - script: ls -lrtha
      - script: touch test.txt
      - script: ls -lrtha
      - saveCache: TestCache
        path: ./test.txt
  - job: Terraform_Apply
    steps:
      - script: "make apply"
      - script: ls -lsrtah
      - restoreCache: TestCache
      - script: ls -lsrtah

