---
trigger:
  - main
stages:
  - stage: TerraformInit
    jobs:
      - job: TerraformInitJob
        steps:
          - script: "make init"
  - stage: TerraformPlan
    jobs:
      - job: TerraformPlanJob
        steps:
          - script: "make plan"
          - script: ls -lrtha
          - script: touch test.txt
          - script: ls -lrtha
  - stage:
    jobs:
    - job: waitForValidation
      displayName: Wait for external validation
      pool: server
      timeoutInMinutes: 4320 # job times out in 3 days
      steps:
      - task: ManualValidation@0
        timeoutInMinutes: 1440 # task times out in 1 day
        inputs:
          notifyUsers: |
            adam.sir@contino.io
          instructions: 'Please validate the build configuration and resume'
          onTimeout: 'resume'
  - stage: TerraformApply
    jobs:
      - job: Terraform_Apply
        steps:
          - script: "make apply"
          - script: ls -lsrtah
