---
trigger:
  - main
stages:
  - stage: TerraformInit
    jobs:
      - job: TerraformInitJob
        steps:
          - script: "make init"
  - stage: TerraformPlan
    jobs:
      - job: TerraformPlanJob
        steps:
          - script: "make plan"
          - script: ls -lrtha
          - script: touch test.txt
          - script: ls -lrtha
  - stage: TerraformApply
    jobs:
      - job: Terraform_Apply
        steps:
          - script: "make apply"
          - script: ls -lsrtah
